name = "avanilla"
description = "Simple replace in character stream"
version = "0.9.4"

authors = ["Jesper Quorning"]
maintainers = ["Jesper Quorning <jesper.quorning@gmail.com>"]
maintainers-logins = ["jquorning"]
licenses = "MIT OR Apache-2.0"
website = "https://github.com/jquorning/avanilla"
tags = ["avanilla", "ada", "simple", "replace", "character", "string", "stream", "generic", "package", "vanilla"]
