
name = "vanilla"
description = "Simple replace in character stream"
version = "0.9.8"

authors = ["Jesper Quorning"]
maintainers = ["Jesper Quorning <jesper.quorning@gmail.com>"]
maintainers-logins = ["jquorning"]
licenses = "MIT OR Apache-2.0"

website = "https://github.com/jquorning/vanilla"
tags = ["simple", "substitute", "replace", "vanilla"]
project-files = ["vanilla.gpr"]

