
name = "vanilla"
description = "Simple replace in character stream"
version = "0.9.8"

authors = ["Jesper Quorning"]
maintainers = ["Jesper Quorning <jesper.quorning@gmail.com>"]
maintainers-logins = ["jquorning"]
licenses = "MIT OR Apache-2.0"

website = "https://github.com/jquorning/avanilla"
tags = ["avanilla", "ada", "simple", "substitute", "character", "string", "generic", "package", "vanilla"]
project-files = ["vanilla.gpr"]

