name: GNAT (Ada)

on:
  push:
    branches:
    - master
    - main
    - dev
    - dev-*

  pull_request:
    branches:
    - master
    - main
    - dev
    - dev-*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild

    - name: Build
      run: gprbuild -j0 -p -P.alire/vanilla.gpr
      
    - name: Build Test
      run: gprbuild -j0 -p -Ptest/test_replace.gpr

